### ISSUE TITLE
Guides sidebar ordering

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#180]
It was brought up to me that maybe the `Database` section should come after `Getting Started` with `HTTP Routing` being 3rd because when you start a new project, that's generally the next part you go to. (i.e. generate your model, or do your database config stuff).

I'm curious to know what others think on this. What is your normal order of operations when you generate an app for the first time?

* Install Lucky
* Generate Project
* ????
* Profit

**Comment by shortly-portly** [comment]
I think that the ordering if ok for the moment. As a newbie to a framework I want to know how I can display pages and then look at creating models/databases, etc. I think once you are familiar with the framwork then models happens first but by that time you are comfortable finding your way around the docs. cheers.

**Comment by jwoertink** [comment]
Cool. Thanks for the input!

**Comment by vlazar** [comment]
To me the current top-down approach makes sense e.g.  Actions -> Pages -> Database (HTTP and Routing -> Frontend -> Database sections). And then less frequent APIs, Auth and so on.

I also think there is a difference between good order for reading the guide and normal order of developing an app. It can be different for different people. Some may want to start from the bottom (Database), some from the top (Action).

**Comment by jwoertink** [comment]
Yeah, that makes sense. I'll let a few more chime in before closing this, but it sounds like the current ordering makes most sense.

**Comment by vlazar** [comment]
@jwoertink 
> If it looks like a duck, and it quacks like a duck…you should not be so quick to jump to conclusions. 

I mean don't rush closing this. Discussions take time 😉

**Comment by jaydorsey** [comment]
It's been a while since I've been thru the guides, but the last time I went thru them I did notice that Database seemed out of order from what I expected (config & overview earlier than routing)

I have rails experience, so not sure if the experience is different for people that don't have it

Edit: the reason I expected this, I think, is that coming over from rails I expected to config database, run some type of scaffolding command and see a model + routes + frontend generated a la rails scaffolding. e.g. something that was a "good enough" place to start exploring so I could see the file & folder locations

**Comment by jwoertink** [comment]
I'm going to close this out now. After some time, the guides are starting to flesh out more, and more guides are being added. I think the current setup is fine. Thanks everyone!
