### ISSUE TITLE
Document Avram model reload

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website#242]
https://github.com/luckyframework/avram/pull/324

**Comment by jwoertink** [comment]
This is kind of a tough one. On the one hand, this is a model specific method, but since it doesn't deal with setting up or writing a model, putting it in the model guides probably doesn't make sense. It could go in the query guides, but is that really where you'd expect to look to find a random method you can call on a model? Technically we have docs on `delete` which are model specific and on the query page, so maybe not horrible?

Now, really where I'd expect this would be in the testing guides... I can't really think of any time I've needed to do this outside of testing. What are your thoughts?

**Comment by paulcsmith** [comment]
I’m thinking the querying guide. Also I think it is useful for doing preloads one a given model. For example, you save a new blog post and then want to reload the post so you can preload the comments, and the comments users, and the users avatars. 

So it’s useful for reloading fresh data but also for reloading with preloads

Maybe we mention it briefly in a testing guide at some point but I’m ok with it mostly being in the query guide. Does that sound good?
