### ISSUE TITLE
Build command should use the `--release` flag

### ISSUE THREAD

**Issue by akadusei** [luckyframework/website#295]
https://github.com/luckyframework/website/blob/79bea9ff802f0e5888e429c162716adf7a777296/src/actions/guides/getting-started/installing.cr#L158

Suggested change:

```plain
crystal build --release src/lucky.cr
```

**Comment by paulcsmith** [comment]
Hi there @akadusei! We used to include that but it makes compilation *much* longer and the performance benefits are not really noticeable since the CLI is used just to start the tasks and generate a project.

I'll go ahead and close this, but feel free to compile in release mode if you want that extra speed boost!
