### ISSUE TITLE
Should these 2 dependencies be mentioned somewhere?

### ISSUE THREAD

**Issue by vishalsodani** [luckyframework/website#640]
Hi,

I found 2 issues while compiling this this project. The compilation process aborted twice due to missing `cmake` and `libxml2-dev`. I am using Ubuntu 18.04.

**Comment by jwoertink** [comment]
Ah, nice catch. That's probably because of either the [cmark](https://github.com/luckyframework/website/blob/master/shard.yml#L26-L27) shard or the [myhtml](https://github.com/luckyframework/website/blob/master/shard.yml#L32-L33) shard... Maybe both? 🤔 

We could probably mention (which ever shard it is) on the [README](https://github.com/luckyframework/website#setting-up-the-project) that those are required.
