### ISSUE TITLE
Arrays in params section outdated

### ISSUE THREAD

**Issue by franciscoGPS** [luckyframework/website#650]
It looks like support for `get_all` was deprecated from Avram, but the Lucky website still points on that direction. 

![image](https://user-images.githubusercontent.com/6760672/118411487-791a2300-b65a-11eb-8ff9-df26cacc9753.png)

**Comment by jwoertink** [comment]
I don't think `get_all` was deprecated? 🤔  https://github.com/luckyframework/lucky/blob/master/src/lucky/params.cr#L163-L173 Param methods are actually defined in Lucky. It is a little confusing because Lucky includes the `Avram::Paramable` module so Avram Operations have knowledge of params https://github.com/luckyframework/lucky/blob/master/src/lucky_avram/ext/lucky/params.cr#L2 but when it comes to docs, `params` is used in the `Lucky::Action` context and will refer to `Lucky::Params`.

Are you getting any deprecation warnings when trying to use it?

**Comment by matthewmcgarvey** [comment]
`get_all` is rather new. Avram just doesn't use it

**Comment by jwoertink** [comment]
I'm going to close this because I think the current documentation is valid for now. This will probably change after next release and we can open up new issues at that time.
