### ISSUE TITLE
Show the current Lucky version

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/website#77]
One thing I do frequently when I visit a project's site is see what the latest version is. Sometimes I need to see if the version I'm using is the latest, or how far behind I may be. Having a way to visually see the latest version on the home page would be great. Maybe this also links to a page showing the releases with their release date.

**Comment by robertguss** [comment]
I would be happy to add this. Do you have an idea of where you would like it displayed? Maybe somewhere in the header, or do you just want it on the homepage?

We could also use the github api to dynamically add the version number so that it is always up to date via `curl https://api.github.com/repos/luckyframework/lucky/tags` We could then link the version number to https://github.com/luckyframework/lucky/releases. The only catch is that if you do not authenticate with the api you can only make 60 requests per hour, otherwise you will need authentication. 

Let me know what you think.

**Comment by jwoertink** [comment]
The home page is where it should be, but i'm not sure where. We don't want anything cheesy. Just simple information that mentions the current latest release of Lucky, and it should link to the [install guides](https://www.luckyframework.org/guides/getting-started/installing). 

I don't think it needs to get crazy connecting to the github API. There's a [class you can use](https://github.com/luckyframework/website/blob/master/src/models/lucky_cli_version.cr) in the repo already.

Thanks!

**Comment by paulcsmith** [comment]
I'm thinking we put it at the top of the guides in place of "All guides" -> "Lucky vX.X.X"

<img width="590" alt="Screen Shot 2019-08-12 at 11 05 36 AM" src="https://user-images.githubusercontent.com/22394/62875554-38f17800-bcf1-11e9-97e6-93703dd46799.png">

**Comment by jwoertink** [comment]
I like that idea ^

**Comment by paulcsmith** [comment]
And once we have versioned guides #78 this would be a drop down with the most recently released version selected by default
